#pragma once

#include <QtWidgets/QMainWindow>
#include <QResizeEvent>

#include "ui_SuperComputing.h"
#include "BubbleSortManager.h"
#include "MergeSortManager.h"
#include "QuickSortManager.h"

/**
 * @class SuperComputing
 * @brief Main application window for sorting algorithm benchmarks.
 */
class SuperComputing : public QMainWindow
{
    Q_OBJECT

public:
    /**
     * @brief Constructs the main window.
     * @param parent Pointer to the parent widget.
     */
    SuperComputing(QWidget* parent = nullptr);

    /**
     * @brief Destroys the main window.
     */
    ~SuperComputing();

private:
    Ui::SuperComputingClass ui; ///< UI instance generated by Qt Designer.

    /**
     * @brief Loads and displays an image in a specific frame.
     * @param imagePath Path to the image file.
     * @param frame Target UI frame.
     */
    void loadImage(const QString& imagePath, QFrame* frame);

    /**
     * @brief Generates a vector of random data.
     * @tparam T Type of data (e.g., int, float).
     * @param elements Number of elements to generate.
     * @return Vector containing the generated data.
     */
    template <typename T>
    std::vector<T> generateRandomData(int elements);

    /**
     * @brief Executes the sorting benchmark and updates the UI and CSV logs.
     * @tparam T Type of data.
     * @param manager Reference to the sorting manager.
     * @param elements Number of elements to sort.
     * @param out Output text stream for CSV logging.
     * @param typeName Name of the data type (e.g., "Integer").
     * @param lblSeq Label for sequential execution time.
     * @param lblMulti Label for multithreaded execution time.
     * @param lblCuda Label for CUDA execution time.
     * @param lblOmp Label for OpenMP execution time.
     * @param tblSeq Table for sequential sorted results.
     * @param tblMulti Table for multithreaded sorted results.
     * @param tblCuda Table for CUDA sorted results.
     * @param tblOmp Table for OpenMP sorted results.
     */
    template <typename T>
    void executeBenchmark(ISortManager<T>& manager, int elements, QTextStream& out, const QString& typeName,
        QLabel* lblSeq, QLabel* lblMulti, QLabel* lblCuda, QLabel* lblOmp,
        QTableWidget* tblSeq, QTableWidget* tblMulti, QTableWidget* tblCuda, QTableWidget* tblOmp);

    /**
     * @brief Populates a UI table with the provided data.
     * @tparam T Type of data.
     * @param table Pointer to the target QTableWidget.
     * @param data Vector containing the data to display.
     */
    template <typename T>
    void fillTable(QTableWidget* table, const std::vector<T>& data);

private slots:
    /** @brief Handler for the Bubble Sort run button. */
    void onBubbleSortButtonClicked();

    /** @brief Handler for the Merge Sort run button. */
    void onMergeSortButtonClicked();

    /** @brief Handler for the Quick Sort run button. */
    void onQuickSortButtonClicked();

    /** @brief Handler for the Refresh Charts button. */
    void onRefreshChartsButtonClicked();

    /** @brief Handler for the Generate PDF Report button. */
    void onGenerateReportButtonClicked();

    /** @brief Handler for deleteing files*/
    bool onClearFilesActionButtonClicked();

    /** @brief Handler for run/generate all tests at one*/
	void onRunAllTestsButtonClicked();

protected:
    /**
     * @brief Handles window state changes (e.g., maximizing/restoring the window).
     * @param event The window state change event.
     */
    void changeEvent(QEvent* event) override;
};